#!/bin/bash

# Switch to other GeoQuest Variant

if [ "$#" -ne 1 ]; then
    echo "Illegal number of parameters - just specify product name."
fi

# Set basic variables:

baseDir=/Users/muegge/projects/qv-geoquest/QV_GQ_Player_Android/GQ_Android/

# Delete included directory in assets first, sinde this should not be kept:

rm -rf ${baseDir}assets/included/


# Copy resources in place, i.e. logos, name etc.

cp -r ${baseDir}products/$1/  $baseDir